const colorMap = {
    // '1': 'Aqua',
    '11': 'Black',
    // '3': 'Brick Yellow',
    '7': 'Bright Blue',
    // '1': 'Bright Bluish Green',
    '6': 'Bright Green',
    '4': 'Bright Orange',
    // '1': 'Bright Purple',
    '5': 'Bright Red',
    // '1': 'Bright Reddish Violet',
    '3': 'Bright Yellow',
    // '1': 'Bright Yellowish Green',
    // '1': 'Cool Yellow',
    // '1': 'Dark Azur',
    '120': 'Dark Brown',
    // '1': 'Dark Green',
    '68': 'Dark Orange',
    '85': 'Dark Stone Grey',
    '63': 'Earth Blue',
    // '1': 'Earth Green',
    // '1': 'Flame Yellowish Orange',
    // '1': 'Light Purple',
    // '1': 'Light Royal Blue',
    // '1': 'Medium Azur',
    '42': 'Medium Blue',
    // '1': 'Medium Lavender',
    // '1': 'Medium Lilac',
    // '1': 'Medium Nougat',
    '86': 'Medium Stone Grey',
    // '1': 'New Dark Red',
    // '1': 'Olive Green',
    '88': 'Reddish Brown',
    // '1': 'Sand Green',
    '2': 'Sand Yellow',
    '77': 'Silver Metallic',
    // '1': 'Spring Yellowish Green',
    '14': 'Tr. Blue',
    // '1': 'Tr. Bright Green',
    '18': 'Tr. Bright Orange',
    // '1': 'Tr. Brown',
    '20': 'Tr. Green',
    '15': 'Tr. Light Blue',
    // '1': 'Tr. Medium Reddish Violet',
    '17': 'Tr. Red',
    '19': 'Tr. Yellow',
    // '1': 'Transparent',
    // '1': 'Vibrant Coral',
    // '1': 'Warm Gold',
    '1': 'White',
    '66': 'Metallic Dark Grey',
    '999': "uknow"
}
module.exports = colorMap;