export enum ActionTypes {
    SET_LIST_GET = 'SET_LIST_GET',
    SET_LIST_GET_FAIL = 'SET_LIST_GET_FAIL',
    SET_DETAILS_GET = 'SET_DETAILS_GET',
    SET_DETAILS_GET_FAIL = 'SET_DETAILS_GET_FAIL',
    SET_BRICKS_LIST_GET = 'SET_BRICKS_LIST_GET',
    SET_BRICKS_LIST_GET_FAIL = 'SET_BRICKS_LIST_GET_FAIL',
}