export enum ActionTypes {
    SET_LIST_GET = 'SET_LIST_GET',
    SET_LIST_GET_FAIL = 'SET_LIST_GET_FAIL',
    SET_DETAILS_GET = 'SET_DETAILS_GET',
    SET_DETAILS_GET_FAIL = 'SET_DETAILS_GET_FAIL',
    SET_BRICKS_LIST_GET = 'SET_BRICKS_LIST_GET',
    SET_BRICKS_LIST_GET_FAIL = 'SET_BRICKS_LIST_GET_FAIL',
    BRICKS_BALANCE_LEGO_PIRATES_SHIP_BRICK_LIST_GET = 'BRICKS_BALANCE_LEGO_PIRATES_SHIP_BRICK_LIST_GET',
    BRICKS_BALANCE_LEGO_PIRATES_SHIP_BRICK_LIST_GET_FAIL = 'BRICKS_BALANCE_LEGO_PIRATES_SHIP_BRICK_LIST_GET_FAIL',
}